apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-metrics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-metrics.selectorLabels" . | nindent 8 }}
        tags.datadoghq.com/env:     {{ .Values.datadog.env | quote }}
        tags.datadoghq.com/service: {{ .Values.datadog.service | quote }}
        tags.datadoghq.com/version: {{ .Values.datadog.version | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}